config/routes.rb
Supermodel::Application.routes.draw do   

	get 'register' => 'users#new', :as => 'register'
	get 'login' => 'sessions#new', :as => 'login'
	get 'logout' => 'sessions#destroy', :as => 'logout' 
	
	resources :sessions, :password_resets
	resources :users, :path => '/' do
		resources :portfolios
		resources :contact_infos
	end		
	
	root :to => 'users#index' 
	match '/:id' => 'users#show' 
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
	belongs_to :user
	attr_accessible :phone, :facebook
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	belongs_to :user	
	attr_accessible :height, :bust, :waist, :hips, :shoes, :eyes, :hair, 
					:image_1, :image_2, :image_3, :suit, :inseam
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	
	attr_accessible :first_name, :last_name, :picture, :sex
  
end

app/models/user.rb
class User < ActiveRecord::Base 
	before_save :encrypt_password
	before_create { generate_token(:auth_token) }
	after_create :create_portfolio, :create_contact_info
	
	attr_accessible :name, :email, :password, :gender, :photo_1, :photo_2, :photo_3
	attr_accessor :password
	
	default_scope :order => 'name'
	
	has_one :portfolio, :dependent => :destroy
	has_one :contact_info, :dependent => :destroy	
	
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email, :name
	validates_uniqueness_of :email
	
	has_friendly_id :name, :use_slug => true, :approximate_ascii => true,
					:reserved_words => ['new', 'users', 'contact', 'about', 'male', 'female', 'portfolios']
	
	  
	def create_portfolio
		build_portfolio.save(:validate => false)
	end
	
	def create_contact_info
		build_contact_info.save(:validate => false)
	end
	
	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end
	
	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end
	
	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
	
	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
	
	def next_user
		self.class.first(:conditions => ["name > ?", name], :order => "name asc")
	end
	
	def previous_user
		self.class.first(:conditions => ["name < ?", name], :order => "name desc")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery 
	helper_method :current_user
	
	private
	def current_user
		@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
	end
	
	def authenticate_user!
		if current_user.nil?
			redirect_to login_url, :alert => "You must first log in to access this page"
		end
	end
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
	def update
		@user = User.find(params[:user_id]) 
		@contact_info = @user.contact_info.update_attributes(params[:contact_info])
		redirect_to edit_user_path(@user), notice: 'Contact Info was successfully updated.'
	end
	
	def show
		@user = User.find(params[:user_id])
		@contact_info = @user.contact_info 
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	def new
	end
	
	def create
		user = User.find_by_email(params[:email])
		user.send_password_reset if user
		redirect_to root_url, :notice => 'An email has been sent with password reset instructions.'
	end
	
	def edit
		@user = User.find_by_password_reset_token!(params[:id])
	end
	
	def update
		@user = User.find_by_password_reset_token!(params[:id]) 
		if @user.password_reset_sent_at < 2.hours.ago
			redirect_to new_password_reset_path, :alert => "Password reset has expired."
		elsif @user.update_attributes(params[:user])
			redirect_to root_url, :notice => "Password has been reset!"
		else
		render :edit, :alert => "Penis"
		end
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	def update
		@user = User.find(params[:user_id]) 
		@portfolio = @user.portfolio.update_attributes(params[:portfolio])
		redirect_to edit_user_path(@user), notice: 'Portfolio was successfully updated.'
	end
	
	def show
		@user = User.find(params[:user_id])
		@portfolio = @user.portfolio 
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def create
		@user = User.find(params[:user_id])
		@profile = @user.create_profile(params[:profile])
		redirect_to user_path(@user)
	end
	
	def show
		@user = User.find(params[:user_id])
		@profile = @user.profile 
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end 
	
	def create
		user = User.authenticate(params[:email], params[:password])		
		if user
			if params[:remember_me]
				cookies.permanent[:auth_token] = user.auth_token
			else
				cookies[:auth_token] = user.auth_token
			end			
			redirect_to root_url, :notice => 'Logged in!'
		else
			redirect_to new_session_url, :notice => 'Invalid email or password'
		end
	end
	
	def destroy
		cookies.delete :auth_token
		redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!, :only => [:edit, :update, :destroy]
	 
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def show
    @user = User.find(params[:id])  
	@portfolio = @user.portfolio
	@contact_info = @user.contact_info
	@users = User.all
	@title = @user.name
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end 
  
  def new
    @user = User.new
	@title = 'Register'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
 
  def edit
    @user = User.find(params[:id]) 
	redirect_to root_url unless current_user == @user
	
	@title = 'Editing ' + @user.name
	@portfolio = @user.portfolio
	@contact_info = @user.contact_info
  end
 
  def create
    @user = User.new(params[:user])  

    respond_to do |format|
      if @user.save
        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully created.' }
        format.json { render json: edit_user_path(@user), status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to edit_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = 'PureModels'
		if @title.nil?
			base_title
		else
			"#{@title} | #{base_title}"
		end		
	end
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact_infos/_contact_info.html.erb
<div id="contact_info" class="tab_content">
	<% if @user.contact_info.phone.blank? && current_user == @user then %>
		<p><strong>There's nothing here yet!</strong><br />
		Please enter your contact info <br />
		by visiting your <%= link_to "edit profile", edit_user_url(@user) %> page.<br />
		This way modeling agencies can contact you easily.</p>
	<% elsif @user.contact_info.phone.blank? && current_user != @user %>
		<p><strong>There's nothing here yet!</strong><br />This user has not entered any contact info yet.</p>
	<% else %>
		<ul>
			<li>
				<div class="label">Phone</div>
				<%= @user.contact_info.phone %>
			</li>
				
			<li>
				<div class="label">Facebook</div>
				<%= link_to "View Profile", @user.contact_info.facebook, :target => :blank %>
			</li>
		</ul>
	<% end %>
</div>

app/views/contact_infos/_form.html.erb
<div id="contact_info" class="tab_content">
	<%= form_for([@user, @contact_info]) do |f| %>
		<div class="field">
			<%= f.label :phone %><br />
			<%= f.text_field :phone %>
		</div>
		<div class="field">
			<%= f.label :facebook %><br />
			<%= f.text_field :facebook %>
		</div> 
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>  
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= stylesheet_link_tag "application" %>  
		<%= csrf_meta_tags %> 
	</head>
	<body>
		<div id="top_bar"> 	
			<ul>  
				<% if current_user %>	
					<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>   
					
				<% else %>
					<li>Are you a model?</li>
				<% end %>
			</ul>  
			
			
			<div class="auth">
				<% if current_user %>
					<%= current_user.name %> | 
					<%= link_to "Log out", logout_path %>
				<% else %>
					<%= link_to "Register", register_path %> | 
					<%= link_to "Login", login_path %>			
				<% end %>
			</div>
		</div>
		<header>
			<div class="logo">
				<h1><%= link_to "PureModels", root_path %></h1>
			</div>
			
			<nav>
				<ul> 
					<li><a href="/male">Male</a></li>
					<li><a href="/female">Female</a></li>
					<li><a href="/about">About</a></li>
					<li><a href="/contact">Contact</a></li> 
				</ul> 
			</nav>
		</header>
		
		
		<section id="container"> 
			<%- flash.each do |k, v| %>
				<div id="<%= k %>"><%= v %></div>
			<% end %> 
			<%= yield %>
		</section>
		
		<footer> 
		</footer>
		<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js", "rails", "shadowbox" %> 
		<script>
			$(document).ready(function(){
				//dropdown navigation
				$("#name_dropdown").change(function() {
					window.location.href = "http://puremodels.heroku.com/" + $(this).val();
				});	  
				
				  
				//tabs 
				var tabContents = $(".tab_content").hide(), 
					tabs = $(".tab_nav li");

				tabs.first().addClass("active").show();
				tabContents.first().show();

				tabs.click(function() {
					var $this = $(this), 
						activeTab = $this.find('a').attr('href');
						history.pushState(null, '', activeTab);
					
					if(!$this.hasClass('active')){
						$this.addClass('active').siblings().removeClass('active');
						tabContents.hide().filter(activeTab).fadeIn();
					}
					
					return false;
				});
				
				$(window).bind('popstate', function(){
					$.getScript(location.href);
				});				
			});

			Shadowbox.init();
		</script>
	</body>
</html> 

app/views/password_resets/edit.html.erb
<h2>Reset Password</h2>

<div id="profile">
	<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
  
		<div class="field">
			<%= f.label :password %><br />
			<%= f.password_field :password %>
		</div> 
		<div class="field">
			<%= f.label :password_confirmation %><br />
			<%= f.password_field :password_confirmation %>
		</div> 
		<div class="actions">
			<%= f.submit "Update Password" %>
		</div>
	<% end %>
</div>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email, params[:email] %>
	</div>
	
	<div class="actions">
		<%= submit_tag("Reset Password") %>
	</div>
<% end %>

app/views/portfolios/_form.html.erb
<div id="portfolio" class="tab_content">
	<% if @user.gender == "female" %>
		<%= form_for([@user, @portfolio]) do |f| %>
			<div class="field">
				<%= f.label :height %><br />
				<%= f.text_field :height %>
			</div>
			<div class="field">
				<%= f.label :bust %><br />
				<%= f.text_field :bust %>
			</div>
			<div class="field">
				<%= f.label :waist %><br />
				<%= f.text_field :waist %>
			</div>	 
			<div class="field">
				<%= f.label :hips %><br />
				<%= f.text_field :hips %>
			</div>
			<div class="field">
				<%= f.label :shoes %><br />
				<%= f.text_field :shoes %>
			</div>
			<div class="field">
				<%= f.label :eyes %><br />
				<%= f.text_field :eyes %>
			</div>
			<div class="field">
				<%= f.label :hair %><br />
				<%= f.text_field :hair %>
			</div> 
			
			<div class="actions">
				<%= f.submit %>
			</div> 
		<% end %> 
	<% else %>
		<%= form_for([@user, @portfolio]) do |f| %>
			<div class="field">
				<%= f.label :height %><br />
				<%= f.text_field :height %>
			</div>
			<div class="field">
				<%= f.label :suit %><br />
				<%= f.text_field :suit %>
			</div>
			<div class="field">
				<%= f.label :waist %><br />
				<%= f.text_field :waist %>
			</div>	 
			<div class="field">
				<%= f.label :inseam %><br />
				<%= f.text_field :inseam %>
			</div>
			<div class="field">
				<%= f.label :shoes %><br />
				<%= f.text_field :shoes %>
			</div>
			<div class="field">
				<%= f.label :eyes %><br />
				<%= f.text_field :eyes %>
			</div>
			<div class="field">
				<%= f.label :hair %><br />
				<%= f.text_field :hair %>
			</div> 
			
			<div class="actions">
				<%= f.submit %>
			</div> 
		<% end %> 
	<% end %>
</div>

app/views/portfolios/_portfolio.html.erb
<div id="portfolio" class="tab_content">	
	<% if @user.portfolio.height.blank? && current_user == @user then %>
		<p><strong>There's nothing here yet!</strong><br />
		Please enter your details by visiting your <%= link_to "edit profile", edit_user_url(@user) %> page.</p>
	<% elsif @user.portfolio.height.blank? && current_user != @user %>
		<p><strong>There's nothing here yet!</strong><br />This user has not entered any details in his or her profile yet.</p>
	<% else %>
		<% if @user.gender == "female" %>
			<ul>
				<li>
					<div class="label">Height</div>
					<%= @user.portfolio.height %>
				</li>
				
				<li>
					<div class="label">Bust</div>
					<%= @user.portfolio.bust %>
				</li>

				<li>
					<div class="label">Waist</div>
					<%= @user.portfolio.hips %>
				</li>

				<li>
					<div class="label">Hips</div>
					<%= @user.portfolio.hips %>
				</li>

				<li>
					<div class="label">Shoes</div>
					<%= @user.portfolio.shoes %>
				</li>

				<li>
					<div class="label">Eyes</div>
					<%= @user.portfolio.eyes %>
				</li>

				<li>
					<div class="label">Hair</div>
					<%= @user.portfolio.hair %>
				</li>
			</ul>
		<% else %>
			<ul>
				<li>
					<div class="label">Height</div>
					<%= @user.portfolio.height %>
				</li>
				
				<li>
					<div class="label">Suit</div>
					<%= @user.portfolio.suit %>
				</li>

				<li>
					<div class="label">Waist</div>
					<%= @user.portfolio.waist %>
				</li>

				<li>
					<div class="label">Inseam</div>
					<%= @user.portfolio.inseam %>
				</li>

				<li>
					<div class="label">Shoes</div>
					<%= @user.portfolio.shoes %>
				</li>

				<li>
					<div class="label">Eyes</div>
					<%= @user.portfolio.eyes %>
				</li>

				<li>
					<div class="label">Hair</div>
					<%= @user.portfolio.hair %>
				</li>
			</ul>
		<% end %>
	<% end %>
</div>

app/views/users/_account_settings.html.erb
<div id="account_settings" class="tab_content">
	<%= form_for(@user) do |f| %>
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
 
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div> 
		<div class="field">
			<%= f.label :password %><br />
			<%= f.password_field :password %>
		</div> 
		<div class="field">
			<%= f.label :password_confirmation %><br />
			<%= f.password_field :password_confirmation %>
		</div> 
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/users/_edit_form.html.erb
<div id="profile" class="tab_content">
	<%= form_for(@user) do |f| %>
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
			<%= f.label :name, "Full Name" %><br />
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :photo_1, "Photo" %><br />
			<%= f.text_field :photo_1 %>
		</div>
		<div class="field">
			<%= f.label :photo_2, "Photo 2" %><br />
			<%= f.text_field :photo_2 %>
		</div>
		<div class="field"> 
			<%= f.radio_button(:gender, "male") %>
			<%= f.label(:gender, "Male") %>
			<%= f.radio_button(:gender, "female") %>
			<%= f.label(:gender, "Female") %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/users/_form.html.erb
<div id="profile" class="tab_content">
	<%= form_for(@user) do |f| %>
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

				<ul>
					<% @user.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
			<%= f.label :name, "Full Name" %><br />
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :photo_1, "Photo" %><br />
			<%= f.text_field :photo_1 %>
		</div>
		<div class="field">
			<%= f.label :photo_2, "Photo 2" %><br />
			<%= f.text_field :photo_2 %>
		</div>
		<div class="field"> 
			<%= f.radio_button(:gender, "male") %>
			<%= f.label(:gender, "Male") %>
			<%= f.radio_button(:gender, "female") %>
			<%= f.label(:gender, "Female") %>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing <%= @user.name %></h1>

<div id="content">	
	<%= render "edit_form" %>   
	<%= render "portfolios/form" %>
	<%= render "contact_infos/form" %>
	<%= render "account_settings" %>
</div>

<div class="content_bot">
	<ul class="tab_nav">
		<li><a href="#profile">Profile</a></li>
		<li><a href="#portfolio">Portfolio</a></li>
		<li><a href="#contact_info">Contact Info</a></li>
		<li><a href="#account_settings">Account</a></li>
	</ul>
	
	<div class="crud">
		<%= link_to "Show", @user %> |
		<%= link_to "Back", :back %> |
		<strong><%= link_to "Destroy", @user, confirm: "Are you sure?", :method => :delete %></strong>
	</div>
</div>

app/views/users/index.html.erb
<ul class="models_list">	
<% @users.each do |user| %> 
	<% unless user.photo_1.blank? %>
	<li>
		<%= link_to image_tag(user.photo_1, :width => "175", :height => "131"), user.friendly_id %>
		<%= link_to user.name, user.friendly_id, :class => "model-name" %>
	</li>
	<% end %>
<% end %>
</ul> 

<div class="clr"></div> 

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/users/show.html.erb
 <h1><%= @user.name %></h1>
 
<span class="next_model_container"><%= link_to(">", @user.next_user, :class => "next_model", :title => "Next Model") if @user.next_user %></span>
<span class="previous_model_container"><%= link_to("<", @user.previous_user, :class => "previous_model", :title => "Previous Model") if @user.previous_user %></span>

<div id="content">	
	<%= link_to image_tag(@user.photo_1, :class => "photo", :alt => @user.name, :width => "350", :height => "450"), @user.photo_1, :rel => "shadowbox[portfolio]" %>
	<%= link_to image_tag(@user.photo_2, :class => "photo", :alt => @user.name, :width => "350", :height => "450"), @user.photo_2, :rel => "shadowbox[portfolio]", :class => "hidden" %>
	
	<%= render "portfolios/portfolio"  %>   
	<%= render "contact_infos/contact_info" %>
	  
	<span class="photo_caption">Click the photo above to see more</span>	
</div>



<div class="content_bot">
	<%= select_tag "name_dropdown", options_from_collection_for_select(@users, "friendly_id", "name", @user.friendly_id) %>
	
	<div class="crud">
		<% if current_user == @user %>	
			<%= link_to "Edit", edit_user_path(@user) %> |
			<%= link_to "Back", root_url %> |
			<strong><%= link_to "Destroy", @user, confirm: "Are you sure?", :method => :delete %></strong>
		<% else %>
			<%= link_to "Back", root_url %>
		<% end %>
	</div>	
	
	<ul class="tab_nav">
		<li><a href="#portfolio">Portfolio</a></li>
		<li><a href="#contact_info">Contact Info</a></li>
	</ul>
</div>